---
settings:
  name: E-Series
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: it-it,us-en,de-de,es-es,fr-fr,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documenti della serie E
    url: "/index.html"
  - title: Note di rilascio
    entries:
    - title: Cosa c'è di nuovo
      url: "/whats-new.html"
  - title: Iniziare
    entries:
    - title: Scopri i sistemi della serie E
      url: "/task-discover-e-series.html"
  - title: Gestire i sistemi E-Series
    entries:
    - title: Visualizza i tuoi sistemi E-Series
      url: "/task-view-e-series.html"
    - title: Rimuovere un sistema dalla NetApp Console
      url: "/task-remove-e-series.html"
  - title: Conoscenza e supporto
    entries:
    - title: Registrati per ricevere supporto
      url: "/task-support-registration.html"
    - title: Ottieni aiuto
      url: "/task-get-help.html"
  - title: Note legali
    url: "/legal-notices.html"
product-family:
  name: Storage Management
  repo: storage-management-family
